#pragma once

#include <stdint.h>
#include "sepstack_ctx_offsets.h"

#ifdef __cplusplus
extern "C" {
#endif

struct sepstack_context_t;

#ifdef __cplusplus
}

#define CHECK_FIELD_OFFSET(offset_val, field)                                  \
  static_assert(offset_val == __builtin_offsetof(sepstack_context_t, field));

#else
#define CHECK_FIELD_OFFSET(offset_val, field)
#endif


/////////////////////////////////////////

#if defined(__x86_64__) || defined(_M_X64)

typedef struct sepstack_context_t {
  /*          0x0, 0x8, 0x10, 0x18, 0x20, 0x28 */
  uint64_t    rax, rbx,  rcx,  rdx,  rsi,  rdi;
  /*          0x30, 0x38, 0x40, 0x48, 0x50, 0x58, 0x60, 0x68 */
  uint64_t    r8,     r9,  r10,  r11,  r12,  r13,  r14,  r15;
  /*          0x70, 0x78, 0x80, 0x88, 0x90, 0x98, 0xa0, 0xa8 */
  uint64_t    xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7;
  /*          0xb0, 0xb8,  0xc0,  0xc8,  0xd0,  0xd8,  0xe0,  0xe8 */
  uint64_t    xmm8, xmm9, xmm10, xmm11, xmm12, xmm13, xmm14, xmm15;
  /*          0xf0,                         0xf8,            0x100,          0x108 */
  uint64_t    source_frame_ptr, source_stack_ptr, target_frame_ptr, target_stack_ptr;
  /*          0x110,                     0x118 */
  uint64_t    source_prog_ctr, target_prog_ctr;
  /*          0x120,               0x128 */
  uint64_t    source_mxcsr, target_mxcsr; // these are 32-bit, but 64-bit simplifies offsets
  /*          0x130,           0x138 */
  uint64_t    source_fcw, target_fcw; // these are 16-bit, but 64-bit simplifies offsets
  /* end:     0x140 */
} sepstack_context_t;

CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RAX, rax);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RBX, rbx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RCX, rcx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RDX, rdx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RSI, rsi);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_RDI, rdi);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R8, r8);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R9, r9);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R10, r10);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R11, r11);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R12, r12);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R13, r13);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R14, r14);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_R15, r15);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM0, xmm0);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM1, xmm1);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM2, xmm2);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM3, xmm3);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM4, xmm4);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM5, xmm5);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM6, xmm6);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM7, xmm7);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM8, xmm8);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM9, xmm9);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM10, xmm10);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM11, xmm11);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM12, xmm12);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM13, xmm13);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM14, xmm14);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_XMM15, xmm15);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_MXCSR, source_mxcsr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_MXCSR, target_mxcsr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_FCW, source_fcw);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_FCW, target_fcw);

/////////////////////////////////////////

#elif defined(__i386__)

typedef struct sepstack_context_t {
  /*          0x0, 0x4, 0x8, 0xc, 0x10, 0x14 */
  uint32_t    eax, ebx,  ecx,  edx,  esi,  edi;
  /*          0x18 */
  uint64_t    st0;
  /*          0x20,                         0x24,             0x28,             0x2c */
  uint32_t    source_frame_ptr, source_stack_ptr, target_frame_ptr, target_stack_ptr;
  /*          0x30,                        0x34 */
  uint32_t    source_prog_ctr, target_prog_ctr;
  /*          0x38,                 0x3c */
  uint32_t    source_mxcsr, target_mxcsr;
  /*          0x40,             0x44 */
  uint32_t    source_fcw, target_fcw; // these are 16-bit, but 32-bit simplifies offsets
  /* end:     0x48 */
} sepstack_context_t;

CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_EAX, eax);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_EBX, ebx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_ECX, ecx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_EDX, edx);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_ESI, esi);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_EDI, edi);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_ST0, st0);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_MXCSR, source_mxcsr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_MXCSR, target_mxcsr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_FCW, source_fcw);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_FCW, target_fcw);


#elif defined(__aarch64__) || defined(_M_ARM64)

typedef struct u128_t {
  uint64_t low;
  uint64_t high;
} u128_t;

typedef struct sepstack_context_t {
  /*          0x0, 0x8, 0x10, 0x18, 0x20, 0x28, 0x30, 0x38 */
  uint64_t     x0,  x1,   x2,   x3,   x4,   x5,   x6,   x7;
  /*          0x40, 0x48, 0x50, 0x58, 0x60, 0x68, 0x70, 0x78 */
  uint64_t      x8,   x9,  x10,  x11,  x12,  x13,  x14,  x15;
  /*          0x80, 0x88, 0x90, 0x98, 0xa0, 0xa8, 0xb0, 0xb8 */
  uint64_t     x16,  x17,  x18,  x19,  x20,  x21,  x22,  x23;
  /*          0xc0, 0xc8, 0xd0, 0xd8, 0xe0, 0xe8, 0xf0, 0xf8 */
  uint64_t     x24,  x25,  x26,  x27,  x28,  x29,  x30, unused;
  /*          0x100 */
  u128_t       q[32];
  /*          0x300, 0x308 */
  uint64_t     nzcv,  fpsr;
  /*          0x310,                       0x318,            0x320,          0x328 */
  uint64_t    source_frame_ptr, source_stack_ptr, target_frame_ptr, target_stack_ptr;
  /*          0x330,                     0x338 */
  uint64_t    source_prog_ctr, target_prog_ctr;
  /* end:     0x340 */
} sepstack_context_t;

CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X0, x0);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X1, x1);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X2, x2);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X3, x3);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X4, x4);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X5, x5);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X6, x6);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X7, x7);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X8, x8);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X9, x9);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X10, x10);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X11, x11);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X12, x12);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X13, x13);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X14, x14);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X15, x15);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X16, x16);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X17, x17);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X18, x18);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X19, x19);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X20, x20);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X21, x21);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X22, x22);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X23, x23);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X24, x24);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X25, x25);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X26, x26);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X27, x27);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X28, x28);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X29, x29);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_X30, x30);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q0, q[0]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q1, q[1]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q2, q[2]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q3, q[3]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q4, q[4]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q5, q[5]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q6, q[6]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q7, q[7]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q8, q[8]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q9, q[9]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q10, q[10]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q11, q[11]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q12, q[12]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q13, q[13]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q14, q[14]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q15, q[15]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q16, q[16]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q17, q[17]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q18, q[18]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q19, q[19]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q20, q[20]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q21, q[21]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q22, q[22]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q23, q[23]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q24, q[24]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q25, q[25]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q26, q[26]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q27, q[27]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q28, q[28]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q29, q[29]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q30, q[30]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_Q31, q[31]);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_NZCV, nzcv);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_FPSR, fpsr);


#else
#error "Unknown architecture"
#endif

#if !defined(__ASSEMBLER__) && defined(__cplusplus)
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_FRAME_PTR, source_frame_ptr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_STACK_PTR, source_stack_ptr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_FRAME_PTR, target_frame_ptr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_STACK_PTR, target_stack_ptr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_SOURCE_PROG_CTR, source_prog_ctr);
CHECK_FIELD_OFFSET(SEPSTACK_CONTEXT_OFFSET_TARGET_PROG_CTR, target_prog_ctr);
static_assert(SEPSTACK_CONTEXT_TOTAL_SIZE == sizeof(sepstack_context_t));
#undef CHECK_FIELD_OFFSET
#endif
